apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pde.fullname" . }}-config
  namespace: {{ include "pde.namespace" . }}
  labels:
    {{- include "pde.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.backend.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
