apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pde.fullname" . }}-frontend
  namespace: {{ include "pde.namespace" . }}
  labels:
    {{- include "pde.labels" . | nindent 4 }}
    {{- include "pde.frontend.selectorLabels" . | nindent 4 }}
spec:
  {{- if not .Values.frontend.autoscaling.enabled }}
  replicas: {{ .Values.frontend.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "pde.frontend.selectorLabels" . | nindent 6 }}
  strategy:
    {{- toYaml .Values.frontend.strategy | nindent 4 }}
  template:
    metadata:
      labels:
        {{- include "pde.frontend.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /nginx-health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /nginx-health
              port: http
            initialDelaySeconds: 3
            periodSeconds: 10
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
