{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "pde.fullname" . }}-ingress
  namespace: {{ include "pde.namespace" . }}
  labels:
    {{- include "pde.labels" . | nindent 4 }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                {{- if eq .service "backend" }}
                name: backend-svc
                port:
                  number: 8000
                {{- else }}
                name: frontend-svc
                port:
                  number: 80
                {{- end }}
          {{- end }}
    {{- end }}
{{- end }}
